<?xml version="1.0" encoding="utf-8"?><Database Name="Orders" Class="OrderDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlExpress;Initial Catalog=Orders;Integrated Security=True" SettingsObjectName="OrderIssues.Data.Properties.Settings" SettingsPropertyName="OrdersConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Issues" Member="Issues">
    <Type Name="Issue">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="note" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="resolved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Order_Issue" Member="Order" ThisKey="OrderId" OtherKey="id" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="amount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="completed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Order_Issue" Member="Issues" ThisKey="id" OtherKey="OrderId" Type="Issue" />
    </Type>
  </Table>
</Database>